#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message. 
# Create git-msg file with the content of shytikov's answer, and put it in some folder:
#
# make it executable in git bash
# chmod a+x ./.git_hooks/commit-msg

NAME=$(git branch | grep '*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)
TEXT=$(cat "$1" | sed '/^#.*/d')

if [ -n "$TEXT" ]
then
    echo '['"$NAME"'] '$(cat "$1" | sed '/^#.*/d') > "$1"
    if [ -n "$DESCRIPTION" ] 
    then
       echo "" >> "$1"
       echo $DESCRIPTION >> "$1"
    fi
else
    echo "Aborting commit due to empty commit message."
    exit 1
fi